### ISSUE TITLE
Got error on phpunit: Non-abstract method MongoCache\MongoStore::getPrefix()

### ISSUE THREAD

**Issue by sisardor** [navruzm/laravel-mongo-cache#1]
So I tried to use your mongo cache, i installed it everything, but I kept getting error and run your phpunit test, fortunately I was able to fix it.  But anywhere here is error

```
$ vendor/bin/phpunit
PHPUnit 3.7.21 by Sebastian Bergmann.

Configuration read from /var/www/phpunit.xml

PHP Fatal error:  Class MongoCache\MongoStore contains 1 abstract 
method and must therefore be declared abstract or implement the remaining 
methods (Illuminate\Cache\StoreInterface::getPrefix) in 
/var/www/vendor/navruzm/laravel-mongo-cache/src/MongoCache/MongoStore.php 
on line 213
PHP Stack trace: 
....
```

I got this when I called to Cach::get() like this

```
$value = Cache::get('key');
```

I fixed it by adding `public function getPrefix() { }` to MongoStore.php maybe someone else will have this same issue, this may fix it?!. Or am I doing something wrong?
And one more question is ok to use this driver in production??

**Comment by navruzm** [comment]
I will fix this issue. I have never used this driver. But i think you can use this in production without problem. Let me know if you have any problem.
